export const PARAM_ID = ':id([0-9]{1,})'
export const PARAM_OBJECT_ID = ':_id([0-9a-fA-F]{24})'
export const PARAM_KEY_STRING = ':key([0-9a-zA-Z_-]{1,})'
export const PARAM_ID_OR_SLUG_MATCH = '[0-9a-zA-Z_-]{1,}'
export const PARAM_UUID_V4 = ':_id([a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12})'
